import Link from 'next/link';
import { Brain, Zap, Target, Trophy, ArrowRight } from 'lucide-react';

export default function Home() {
  const features = [
    {
      icon: Brain,
      title: 'AI-Powered Questions',
      description: 'Get custom questions generated by advanced AI for any topic you choose.'
    },
    {
      icon: Target,
      title: 'Adaptive Difficulty',
      description: 'Choose from easy, medium, or hard difficulty levels that match your skill.'
    },
    {
      icon: Zap,
      title: 'Instant Results',
      description: 'Get immediate feedback with detailed explanations for every question.'
    },
    {
      icon: Trophy,
      title: 'Track Progress',
      description: 'Monitor your learning journey and see how you improve over time.'
    }
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-purple-50">
      {/* Hero Section */}
      <section className="pt-20 pb-16 px-4 sm:px-6 lg:px-8">
        <div className="max-w-7xl mx-auto text-center">
          <div className="flex justify-center mb-8">
            <div className="flex items-center space-x-3 bg-white rounded-full px-6 py-3 shadow-lg">
              <Brain className="h-8 w-8 text-primary-600" />
              <span className="text-2xl font-bold text-gray-900">Quiz Master AI</span>
            </div>
          </div>
          
          <h1 className="text-4xl md:text-6xl font-bold text-gray-900 mb-6">
            Master Any Topic with
            <span className="text-primary-600 block">AI-Powered Quizzes</span>
          </h1>
          
          <p className="text-xl text-gray-600 mb-8 max-w-3xl mx-auto">
            Challenge yourself with personalized quizzes generated by artificial intelligence. 
            Learn faster, retain more, and track your progress across any subject.
          </p>
          
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link
              href="/setup"
              className="btn-primary inline-flex items-center text-lg px-8 py-4"
            >
              Start Learning Now
              <ArrowRight className="ml-2 h-5 w-5" />
            </Link>
            
            <Link
              href="/auth"
              className="btn-secondary inline-flex items-center text-lg px-8 py-4"
            >
              Sign Up Free
            </Link>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-16 px-4 sm:px-6 lg:px-8 bg-white">
        <div className="max-w-7xl mx-auto">
          <div className="text-center mb-12">
            <h2 className="text-3xl md:text-4xl font-bold text-gray-900 mb-4">
              Why Choose Quiz Master AI?
            </h2>
            <p className="text-xl text-gray-600 max-w-2xl mx-auto">
              Our AI-powered platform adapts to your learning style and helps you master any subject efficiently.
            </p>
          </div>
          
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
            {features.map((feature, index) => (
              <div key={index} className="card text-center hover:shadow-xl transition-shadow">
                <div className="flex justify-center mb-4">
                  <div className="p-3 bg-primary-100 rounded-full">
                    <feature.icon className="h-8 w-8 text-primary-600" />
                  </div>
                </div>
                <h3 className="text-xl font-semibold text-gray-900 mb-2">
                  {feature.title}
                </h3>
                <p className="text-gray-600">
                  {feature.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-16 px-4 sm:px-6 lg:px-8 bg-primary-600">
        <div className="max-w-4xl mx-auto text-center">
          <h2 className="text-3xl md:text-4xl font-bold text-white mb-4">
            Ready to Transform Your Learning?
          </h2>
          <p className="text-xl text-primary-100 mb-8">
            Join thousands of learners who are already using AI to accelerate their education.
          </p>
          <Link
            href="/setup"
            className="bg-white text-primary-600 hover:bg-gray-100 font-semibold py-4 px-8 rounded-lg text-lg transition-colors duration-200 inline-flex items-center"
          >
            Create Your First Quiz
            <ArrowRight className="ml-2 h-5 w-5" />
          </Link>
        </div>
      </section>
    </div>
  );
}
